/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1.0.0
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DwellingMonthConsumption {
  readonly id?: number;
  readonly date?: string;
  readonly month_consumption?: number;
  readonly max_month_consumption?: number;
  readonly month_consumption_percentage?: number;
}
