/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ManagerConfiguration {
  readonly id?: number;
  max_daily_consumption: string;
  hook_price: string;
  readonly release_date?: string;
  readonly discharge_date?: string;
}
