/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ReservoirDetail {
  readonly id?: string;
  city: string;
  road: string;
  number: string;
  water_meter_code: string;
  capacity: string;
  inlet_flow: string;
  outlet_flow: string;
}
