/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1.0.0
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDwellingDetail {
  readonly id?: string;
  readonly city?: string;
  readonly road?: string;
  readonly number?: string;
  readonly residentFullName?: string;
  readonly residentPhone?: string;
  readonly waterMeterCode?: string;
  readonly watermeterLastMonthConsumption?: string;
  readonly latitude?: string;
  readonly longitude?: string;
  readonly isOwner?: string;
  readonly isResident?: string;
}
