# Generated by Django 3.1.5 on 2022-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigureThemeLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField()),
                ('lang', models.TextField()),
            ],
            options={
                'db_table': 'agube_configurethemelang_configurethemelang',
            },
        ),
    ]
