# Generated by Django 3.1.5 on 2022-04-27 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurethemelang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurethemelang',
            name='id',
        ),
        migrations.AddField(
            model_name='configurethemelang',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
