# Generated by Django 3.1.5 on 2022-04-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_configuration'),
        ('configurethemelang', '0002_auto_20220427_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurethemelang',
            name='user',
        ),
        migrations.AddField(
            model_name='configurethemelang',
            name='id',
            field=models.AutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configurethemelang',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.manager'),
            preserve_default=False,
        ),
    ]
