# Generated by Django 3.1.5 on 2022-04-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_configuration'),
        ('configurethemelang', '0003_auto_20220427_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurethemelang',
            name='manager',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='manager.manager'),
        ),
    ]
