# Generated by Django 3.1.5 on 2022-04-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0002_manager_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField()),
                ('lang', models.TextField()),
                ('manager', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='manager.manager')),
            ],
            options={
                'db_table': 'agube_userconfig_userconfig',
            },
        ),
    ]
