# Generated by Django 3.1.5 on 2022-04-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0002_manager_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.person')),
                ('mode', models.TextField()),
                ('lang', models.TextField()),
            ],
            options={
                'db_table': 'agube_userconfig_userconfig',
            },
        ),
    ]
