# Generated by Django 3.1.5 on 2022-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('zoom', models.PositiveIntegerField()),
                ('horizontalDegree', models.IntegerField(default=0)),
                ('verticalDegree', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'agube_geolocation_geolocation',
            },
        ),
    ]
