# Generated by Django 3.1.5 on 2022-04-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocation',
            old_name='horizontalDegree',
            new_name='horizontal_degree',
        ),
        migrations.RenameField(
            model_name='geolocation',
            old_name='verticalDegree',
            new_name='vertical_degree',
        ),
    ]
