# Generated by Django 3.1.5 on 2022-04-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_auto_20220420_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
