# Generated by Django 3.1.5 on 2022-04-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        ('reservoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservoirGeolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.geolocation')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservoir.reservoir')),
            ],
            options={
                'db_table': 'agube_reservoir_reservoir_geolocation',
            },
        ),
    ]
