# Generated by Django 3.1.5 on 2022-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservoir',
            name='capacity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='inlet_flow',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='outlet_flow',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
