# Generated by Django 3.1.5 on 2021-03-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dwelling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('dwelling', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dwelling.dwelling')),
            ],
            options={
                'db_table': 'water_meter',
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterMeterMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(decimal_places=3, max_digits=8)),
                ('date', models.DateTimeField()),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watermeter.watermeter')),
            ],
            options={
                'db_table': 'water_meter_measurement',
                'ordering': ['-date'],
            },
        ),
    ]
