/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Address {
  readonly id?: number;
  is_external?: boolean;
  city: string;
  country: string;
  city_district: string;
  municipality: string;
  postcode: string;
  province: string;
  state: string;
  village?: string;
  road?: string;
}
