/**
 * Auth API
 * Auth API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EnableAccount {
    activation_code: string;
    username: string;
    password: string;
    confirm_password: string;
}
