/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

export interface Geolocation {
  // id is not readonly, frontend needs assign it
  id?: number;
  address: Address;
  latitude: string;
  longitude: string;
  zoom: number;
  horizontal_degree?: number;
  vertical_degree?: number;
  number?: number;
  flat?: string;
  gate?: string;
}
