/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WaterMeterMeasurement {
  readonly id?: number;
  measurement: string;
  date?: Date;
  readonly average_daily_flow?: number;
  readonly max_daily_consumption?: number;
}
