/**
 * Contact Book API
 * Contact Book API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TagContact } from './tagContact';


export interface Contact {
    readonly id?: string;
    readonly manager_id?: number;
    full_name?: string;
    extra_info?: string;
    email?: string;
    phone_number: string;
    readonly tags?: Array<TagContact>;
}
