/**
 * Contact Book API
 * Contact Book API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tag } from './tag';


export interface CreateTags { 
    tags: Array<Tag>;
}
