/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DwellingDetail {
    readonly id?: string;
    water_meter_code: string;
    street: string;
    number: string;
    flat: string;
    gate: string;
    town: string;
    resident_first_name: string;
    resident_phone: string;
}
