/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';


export interface DwellingResident { 
    readonly id?: string;
    readonly dwellingId?: number;
    user: User;
    readonly releaseDate?: string;
    readonly dischargeDate?: string;
}
