/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DwellingDetail {
  readonly id?: string;
  waterMeterCode: string;
  street: string;
  number: string;
  flat: string;
  gate: string;
  town: string;
  residentFirstName: string;
  residentPhone: string;
}
