/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HookPrice } from './hookPrice';


export interface ManagerConfiguration {
    readonly id?: string;
    max_daily_consumption: string;
    hook_price: HookPrice;
}
