/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Paymaster {
  readonly id?: string;
  payment_type?: Paymaster.PaymentTypeEnum;
  iban?: string;
  username: string;
}
// tslint:disable-next-line: no-namespace
export namespace Paymaster {
  export type PaymentTypeEnum = 'BANK' | 'CASH' | 'EXEMPT';
  export const PaymentTypeEnum = {
    BANK: 'BANK' as PaymentTypeEnum,
    CASH: 'CASH' as PaymentTypeEnum,
    EXEMPT: 'EXEMPT' as PaymentTypeEnum,
  };
}
