/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FullAddress } from './fullAddress';
import { WaterMeter } from './waterMeter';


export interface ReservoirCreate { 
    readonly id?: string;
    fullAddress: FullAddress;
    userId: number;
    waterMeter: WaterMeter;
    capacity: string;
    inletFlow: string;
    outletFlow: string;
}
