/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WaterMeterMeasurement } from './waterMeterMeasurement';


export interface WaterMeterDetail { 
    readonly id?: string;
    readonly releaseDate?: string;
    readonly dischargeDate?: string;
    waterMeter: Array<WaterMeterMeasurement>;
}
