/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WaterMeterMeasurement } from './waterMeterMeasurement';

export interface WaterMeterWithMeasurements {
  readonly id?: string;
  readonly code?: string;
  readonly release_dDate?: string;
  readonly discharge_date?: string;
  water_meter: Array<WaterMeterMeasurement>;
}
