# Generated by Django 3.1.5 on 2022-10-05 10:12

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        ('manager', '0003_managermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('geolocation',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geolocation.geolocation')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.manager')),
            ],
            options={
                'db_table': 'agube_springsource_springsource',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('SpringSource'), models.Model),
        ),
    ]
