# Generated by Django 3.1.5 on 2022-10-06 09:35

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_comments_for_dwellings'),
        ('springsource', '0001_create_springsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringSourceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
                ('spring_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='springsource.springsource')),
            ],
            options={
                'db_table': 'agube_springsource_comment',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('ReservoirComment'), models.Model),
        ),
    ]
