# Generated by Django 3.1.5 on 2021-03-03 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('full_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.fulladdress')),
            ],
            options={
                'db_table': 'dwelling',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.TextField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('EXEMPT', 'Exempt')], default='BANK')),
                ('iban', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='DwellingResident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('dwelling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwelling.dwelling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resident',
            },
        ),
        migrations.CreateModel(
            name='DwellingOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('dwelling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwelling.dwelling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.AddField(
            model_name='dwelling',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwelling.payment'),
        ),
    ]
