# Generated by Django 3.1.5 on 2021-03-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dwelling', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.manager'),
        ),
    ]
