# Generated by Django 3.1.5 on 2022-04-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        ('dwelling', '0002_dwelling_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwellingGeolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwelling', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dwelling.dwelling')),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.geolocation')),
            ],
            options={
                'db_table': 'agube_dwelling_dwelling_geolocation',
            },
        ),
    ]
