# Generated by Django 3.1.5 on 2022-05-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwelling', '0002_dwelling_manager'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dwellingowner',
            table='agube_owner_owner',
        ),
    ]
