# Generated by Django 3.1.5 on 2022-05-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwelling', '0003_rename_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DwellingOwner',
        ),
    ]
