# Generated by Django 3.1.5 on 2022-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermetermeasurement',
            name='measurement_diff',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='watermetermeasurement',
            name='measurement',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
