# Generated by Django 3.1.5 on 2022-10-05 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('watermeter', '0002_measurement_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watermetermeasurement',
            old_name='measurement_diff',
            new_name='average_daily_flow',
        ),
    ]
