/**
 * Agube API
 * Agube API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Owner {
    readonly id?: string;
    readonly dwelling_id?: number;
    user: User;
    readonly release_date?: string;
    readonly discharge_date?: string;
}
