/**
 * Subscription API
 * Subscription API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SubscriptionId } from './subscriptionId';


export interface PermissionsHasSubscription {
    readonly id?: string;
    readonly code_ame?: string;
    readonly name?: string;
    readonly subscriptions?: Array<SubscriptionId>;
}
