/**
 * Subscription API
 * Subscription API REST definition
 *
 * OpenAPI spec version: v1
 * Contact: frannabril@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SubscriptionType } from './subscriptionType';


export interface Subscription { 
    readonly id?: string;
    name: string;
    description: string;
    price: string;
    pricePerDay: string;
    type?: SubscriptionType;
}
