# Generated by Django 3.1.5 on 2022-09-13 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reservoir', '0002_reservoir_capacity_upgraded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservoirwatermeter',
            options={'ordering': ['-water_meter__release_date']},
        ),
    ]
