# Generated by Django 3.1.5 on 2022-05-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('dwelling', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.manager'),
        ),
    ]
