# Generated by Django 3.1.5 on 2022-05-12 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dwelling', '0005_rename_resident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DwellingResident',
        ),
    ]
