# Generated by Django 3.1.5 on 2022-09-13 14:43

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0001_comments_for_dwellings'),
        ('dwelling', '0006_moved_resident_to_his_own_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dwellingwatermeter',
            options={'ordering': ['-water_meter__release_date']},
        ),
        migrations.CreateModel(
            name='DwellingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
                ('dwelling', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dwelling.dwelling')),
            ],
            options={
                'db_table': 'agube_dwelling_comment',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('DwellingComment'), models.Model),
        ),
    ]
