# Generated by Django 3.1.5 on 2022-05-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False,
                                      to='auth.user')),
            ],
            options={
                'db_table': 'agube_manager_manager',
            },
        ),
        migrations.CreateModel(
            name='ManagerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_consumption', models.DecimalField(decimal_places=3, max_digits=8)),
                ('hook_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('release_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.manager')),
            ],
            options={
                'db_table': 'agube_manager_configuration',
            },
        ),
    ]
