# Generated by Django 3.1.5 on 2022-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='dwelling_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
