# Generated by Django 3.1.5 on 2022-09-15 07:43

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0002_manager_limit_dwellings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.TextField(default=None, max_length=500, null=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='manager.manager')),
            ],
            options={
                'db_table': 'agube_manager_message',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('ManagerMessage'), models.Model),
        ),
    ]
