# Generated by Django 3.1.5 on 2021-02-25 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.TextField()),
                ('street', models.TextField()),
                ('is_external', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dwelling_address',
                'ordering': ['town', 'street'],
            },
        ),
        migrations.CreateModel(
            name='FullAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('flat', models.TextField(null=True)),
                ('gate', models.TextField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'db_table': 'dwelling_full_address',
                'ordering': ['address__town', 'address__street', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UserFullAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('full_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.fulladdress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dwelling_user_full_address',
            },
        ),
    ]
