# Generated by Django 3.1.5 on 2022-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulladdress',
            name='flat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='gate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
