# Generated by Django 3.1.5 on 2022-04-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20220419_1700'),
        ('address', '0002_full_address_blank_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulladdress',
            name='address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country', 'state', 'city']},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='town',
            new_name='city_district',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='flat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='gate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='geolocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geolocation.geolocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='municipality',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='road',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='village',
            field=models.TextField(blank=True, null=True),
        ),
    ]
