# Generated by Django 3.1.5 on 2022-04-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20220419_1700'),
        ('dwelling', '0004_auto_20220419_1700'),
        ('login', '0002_auto_20220419_1700'),
        ('reservoir', '0003_auto_20220419_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullAddress',
        ),
    ]
