# Generated by Django 3.1.5 on 2022-05-04 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.manager')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agube_person_person',
            },
        ),
        migrations.CreateModel(
            name='PersonConfig',
            fields=[
                ('person',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='person.person')),
                ('mode', models.TextField()),
                ('lang', models.TextField()),
            ],
            options={
                'db_table': 'agube_person_config',
            },
        ),
    ]
