# Generated by Django 3.1.5 on 2022-05-19 09:15

from django.db import migrations, models

import person.models


class Migration(migrations.Migration):
    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to=person.models.person_directory_path),
        ),
    ]
