# Generated by Django 3.1.5 on 2022-05-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('zoom', models.PositiveIntegerField()),
                ('horizontal_degree', models.IntegerField(default=0)),
                ('vertical_degree', models.IntegerField(default=0)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('flat', models.TextField(blank=True, null=True)),
                ('gate', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'db_table': 'agube_geolocation_geolocation',
                'ordering': ['number'],
            },
        ),
    ]
