# Generated by Django 3.1.5 on 2022-09-13 14:43

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'agube_comment',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('Comment'), models.Model),
        ),
    ]
