# Generated by Django 3.1.5 on 2021-09-06 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerconfiguration',
            name='discharge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='managerconfiguration',
            name='hook_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerconfiguration',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 18, 1, 5, 938021, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managerconfiguration',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.manager'),
        ),
        migrations.DeleteModel(
            name='HookPrice',
        ),
    ]
